In [1]:
import numpy as np

In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Apps/miniconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Apps/miniconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Apps/miniconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Apps/miniconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Apps/miniconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Apps/miniconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Apps/miniconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Apps/miniconda\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41

In [3]:
a = np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [8]:
a = np.zeros(11)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
a.nbytes

88

In [10]:
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [11]:
a = np.linspace(10,49,40)
a

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

In [12]:
np.flip(a)

array([49., 48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38., 37.,
       36., 35., 34., 33., 32., 31., 30., 29., 28., 27., 26., 25., 24.,
       23., 22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11.,
       10.])

In [13]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [15]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.random((3, 3, 3))

array([[[0.79162262, 0.34997455, 0.88246685],
        [0.75742196, 0.72361098, 0.74589314],
        [0.71695897, 0.56499536, 0.21962647]],

       [[0.36122164, 0.253471  , 0.90104675],
        [0.55466561, 0.17401491, 0.95772468],
        [0.73025983, 0.58988588, 0.21429277]],

       [[0.61547839, 0.23281671, 0.88816096],
        [0.75451739, 0.49378171, 0.26779128],
        [0.40941033, 0.36293085, 0.74674568]]])

In [17]:
a = np.random.random((10, 10))
print(np.min(a))
print(np.max(a))

0.01660424852267539
0.9832785195128617


In [18]:
a = np.random.random(30)
np.mean(a)

0.4959663445409889

In [19]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])